In [3]:
import numpy as np

In [4]:
import random

In [5]:
arr_2d=np.random.randint(1,100,(5,5))
print(arr_2d)

[[41 58 79 99 46]
 [58 56 74  4 24]
 [46 66 20 29 79]
 [82 19 35 66 33]
 [19 20 86 51 36]]


In [8]:
arr_2d[arr_2d%2==0]


array([58, 46, 58, 56, 74,  4, 24, 46, 66, 20, 82, 66, 20, 86, 36])

In [9]:
np.square

<ufunc 'square'>

In [10]:
np.power(arr_2d,2)

array([[1681, 3364, 6241, 9801, 2116],
       [3364, 3136, 5476,   16,  576],
       [2116, 4356,  400,  841, 6241],
       [6724,  361, 1225, 4356, 1089],
       [ 361,  400, 7396, 2601, 1296]], dtype=int32)

In [11]:
arr_2d=arr_2d.astype(float)
a=arr_2d%2==0
arr_2d[a]=np.sqrt(arr_2d[a])
arr_2d

array([[41.        ,  7.61577311, 79.        , 99.        ,  6.78232998],
       [ 7.61577311,  7.48331477,  8.60232527,  2.        ,  4.89897949],
       [ 6.78232998,  8.1240384 ,  4.47213595, 29.        , 79.        ],
       [ 9.05538514, 19.        , 35.        ,  8.1240384 , 33.        ],
       [19.        ,  4.47213595,  9.2736185 , 51.        ,  6.        ]])

In [12]:
arr=np.linspace(-3,3,50)
arr

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [13]:
def sigmoid(x):
    return 1/(1+np.exp(-x))
print(sigmoid(arr))

[0.04742587 0.05327452 0.05979915 0.06706626 0.07514592 0.08411121
 0.09403734 0.10500059 0.11707679 0.13033963 0.14485842 0.16069565
 0.17790412 0.19652392 0.2165791  0.23807447 0.26099251 0.28529068
 0.3108993  0.33772042 0.3656277  0.39446751 0.42406149 0.45421029
 0.48469866 0.51530134 0.54578971 0.57593851 0.60553249 0.6343723
 0.66227958 0.6891007  0.71470932 0.73900749 0.76192553 0.7834209
 0.80347608 0.82209588 0.83930435 0.85514158 0.86966037 0.88292321
 0.89499941 0.90596266 0.91588879 0.92485408 0.93293374 0.94020085
 0.94672548 0.95257413]


In [14]:
arr2=np.random.randint(1,100,(4,4))
#np.fromfunction(lambda i,j: np.random.randint(),(4,4))#
mat=np.matrix(arr2)
mat

matrix([[27, 49, 65, 49],
        [51, 95, 51, 96],
        [85,  8, 86, 42],
        [56, 23, 17, 34]])

In [20]:
print(mat[1])

[[51 95 51 96]]


In [21]:
mat1=np.diag(mat)
mat1

array([27, 95, 86, 34])

In [27]:
condition=mat/2!=0
mat2=mat[condition]

print(mat2)

[[27 49 65 49 51 95 51 96 85  8 86 42 56 23 17 34]]


In [28]:
arr4= np.random.normal(loc=50,scale=15,size=1000)
arr4

array([ 53.27058881,  34.94066772,  29.54414262,  49.22351063,
        48.33699763,  53.13948641,  39.19593613,  59.43146487,
        44.5391913 ,  41.52431836,  36.13309154,  34.38343161,
        62.07631013,  77.00871196,  68.75528308,  36.00628873,
        41.85371031,  63.36354926,  34.95203518,  44.00063854,
        53.41937349,  41.15720257,  26.43039041,  24.8931722 ,
        50.12039474,  49.65740344,  22.12698184,  43.45367812,
        54.59701023,  51.4307634 ,  33.75286726,  26.91839079,
        70.20564364,  65.64911093,  46.38785198,  52.04071491,
        68.11564615,  52.05071449,  47.18061991,  83.74975406,
        57.10971786,  32.41067637,  56.70926779,  42.26548638,
        69.000638  ,  55.88684072,  64.87878646,  29.69950125,
        40.0516675 ,  55.43081709,  60.61135455,  54.73312325,
        67.50625588,  46.88750996,  28.73857989,  47.55300071,
        49.36403346,   7.42372021,  35.73005782,  34.3524918 ,
        37.41257686,  31.68921763,  52.7747094 ,  43.12